---
defaults: &defaults
  app_name: "pik-cars-dashboard-backend"
  period_in_days_api_token_update: 20
  perion_nsi_update: 300
  period_live_update: 60
  time_shift_first_events_update: 2592000

development:
  <<: *defaults

production:
  <<: *defaults
